
DATA[DATA.length] = { section: "Changelog", noheaders: true }
DATA[DATA.length] = { changelog: "Damage types",			note: "If armor does not give protection against a type, that type is not shown on that armor. Dialogs for buying armor are all similar now and the order for listing protection values is always Weapons/Monsters/Magic/Dragon fire." };
DATA[DATA.length] = { changelog: "Guild specialization",	note: "Each guild has been given some more flavor with what their armor protects against. The Militia has armor designed for protection against weapons, while the Mercenaries armor is more tailored towards fighting beasts. Paladin's armor undoubtedly offers best protection against most advesaries, but the Dragon Hunter's plating is more effective against dragon fire. Fire Magicians robes offer less physical protection, but excell against magical attacks." };
DATA[DATA.length] = { changelog: "Random",	note: "<nobr><li>Addon armors have correct material tags.</li></nobr>" };

DATA[DATA.length] = { section: "Mercenary/Dragon Hunter" };
DATA[DATA.length] = { id: "ruestung_8",		pic: "screens/ruestungen/leichte_soeldnerruestung.jpg",			name: "Light Mercenary Armor",			p_edge: 30,		p_point: 30,	p_fire: 0,		p_magic: 0,		value: 500,		note: "You get it from <b>Lee</b> after you joined the mercenaries (quest <b>'Member of the Mercenaries'</b>)." };
DATA[DATA.length] = { id: "ruestung_9",		pic: "screens/ruestungen/mittlere_soeldnerruestung.jpg",		name: "Medium Mercenary Armor",			p_edge: 45,		p_point: 40,	p_fire: 5,		p_magic: 5,		value: 1000,	note: "You can get it for free from <b>Gorn</b> after you freed him in the Valley of Mines (quest <b>'Rescue Gorn'</b>) or you can buy it from <b>Lee</b> after you finished the quest from <b>Torlof</b> and collected the lease (quest <b>'Collect the rent'</b> or <b>'Drive away the Militia'</b>)." };
DATA[DATA.length] = { id: "ruestung_10",	pic: "screens/ruestungen/schwere_soeldnerruestung.jpg",			name: "Heavy Mercenary Armor",			p_edge: 60,		p_point: 50,	p_fire: 10,		p_magic: 10,	value: 2500,	note: "You can buy it from <b>Lee</b> in chapter 3." };
DATA[DATA.length] = { id: "ruestung_11",	pic: "screens/ruestungen/leichte_drachenjaegerruestung.jpg",	name: "Light Dragon Hunter's Armor",	p_edge: 70,		p_point: 60,	p_fire: 40,		p_magic: 20,	value: 3000,	note: "You get this armor from <b>Bennet</b> after you freed <b>him</b> from jail and went to Xardas (quest <b>'Bennet is in Jail'</b>)." };
DATA[DATA.length] = { id: "ruestung_12",	pic: "screens/ruestungen/mittlere_drachenjaegerruestung.jpg",	name: "Medium Dragon Hunter's Armor",	p_edge: 80,		p_point: 70,	p_fire: 50,		p_magic: 30,	value: 12000,	note: "You can buy this from <b>Jan</b> (the blacksmith in the castle in the Valley of Mines)in chapter 4 after you made sure that he can work in the forge (quest <b>'Jan and the Smithy'</b>). You have to own at least 20 dragon scales. Furthermore you can buy this armor from <b>Bennet</b>, but just like Jan he needs 20 dragon scales for his work." };
DATA[DATA.length] = { id: "ruestung_13",	pic: "screens/ruestungen/schwere_drachenjaegerruestung.jpg",	name: "Heavy Dragon Hunter's Armor",	p_edge: 90,		p_point: 80,	p_fire: 60,		p_magic: 40,	value: 20000,	note: "You will get this armor in chapter 5 from <b>Bennet</b> after you read the almanac in the <b>secret library</b> under the monastery." };

DATA[DATA.length] = { section: "Militia/Paladin" };
DATA[DATA.length] = { id: "ruestung_1",		pic: "screens/ruestungen/leichte_milizruestung.jpg",			name: "Light Militia Armor",			p_edge: 30,		p_point: 40,	p_fire: 0,		p_magic: 0,		value: 600,		note: "You will get it from <b>Lord Andre</b> when you join the militia (quest <b>'Member of the city guard'</b>)." };
DATA[DATA.length] = { id: "ruestung_2",		pic: "screens/ruestungen/schwere_milizruestung.jpg",			name: "Heavy Militia Armor",			p_edge: 50,		p_point: 60,	p_fire: 10,		p_magic: 10,	value: 2500,	note: "You can buy this armor at <b>Engor</b> in the Valley of Mines in chapter 2." };
DATA[DATA.length] = { id: "ruestung_3",		pic: "screens/ruestungen/ritterruestung.jpg",					name: "Knight's Armor",					p_edge: 70,		p_point: 80,	p_fire: 30,		p_magic: 30,	value: 5000,	note: "You get it from <b>Lord Hagen</b> in chapter 3 (after the quest <b>'Bennet is in Jail'</b>)." };
DATA[DATA.length] = { id: "ruestung_4",		pic: "screens/ruestungen/paladinruestung.jpg",					name: "Paladin's Armor",				p_edge: 90,		p_point: 100,	p_fire: 50,		p_magic: 50,	value: 20000,	note: "You can get this armor in chapter 5 when you were in the <b>monastery's basement</b>." };

DATA[DATA.length] = { section: "Novice/Mage" };
DATA[DATA.length] = { id: "ruestung_5",		pic: "screens/ruestungen/novizenrobe.jpg",						name: "Novice's Robe",					p_edge: 25,		p_point: 25,	p_fire: 0,		p_magic: 10,	value: 280,		note: "You get the Novice´s Robe from <b>Pedro</b> in chapter 1 when you join the <b>monastery</b> (quest <b>'How to Get into the Monastery'</b>)." };
DATA[DATA.length] = { id: "ruestung_6",		pic: "screens/ruestungen/feuermagierrobe.jpg",					name: "Fire Mage's Robe",				p_edge:"40,60",p_point:"40,60",p_fire:"10,30",p_magic:"20,40",	value: 500,		note: "You get the robe from <b>Pyrokar</b> in chapter 1 after you have been promoted to Fire Mage (quest <b>'The Test of Fire'</b>).<li>Protection is improved upon reaching the fourth Circle.</li>" };
DATA[DATA.length] = { id: "ruestung_7",		pic: "screens/ruestungen/schwere_feuerrobe.jpg",				name: "Heavy Fire Robe",				p_edge:"70,80",p_point:"70,80",p_fire:"30,40",p_magic:"50,60",	value: 3000,	note: "You get the Heavy Fire Robe from <b>Pyrokar</b> after the Eye of Innos has been healed (quest <b>'The Eye of Innos'</b>).<li>Protection is improved upon reaching the sixth Circle.</li>" };

DATA[DATA.length] = { section: "Guildless" };
DATA[DATA.length] = { id: "ruestung_22",	pic: "screens/ruestungen/buerger_kleidung.jpg",					name: "Citizen's Clothing 1",			p_edge: 10,		p_point: 10,	p_fire: 0,		p_magic: 0,		value: 120,		note: "You can find the clothing in the right chest of the storage of Matteo" };
DATA[DATA.length] = { id: "ruestung_23",	pic: "screens/ruestungen/buerger_kleidung1.jpg",				name: "Citizen's Clothing 2",			p_edge: 10,		p_point: 10,	p_fire: 0,		p_magic: 0,		value: 120,		note: "You can find the clothing in the right chest of the storage of Matteo" };
DATA[DATA.length] = { id: "ruestung_24",	pic: "screens/ruestungen/buerger_kleidung2.jpg",				name: "Citizen's Clothing 3",			p_edge: 10,		p_point: 10,	p_fire: 0,		p_magic: 0,		value: 120,		note: "You can find the clothing in the right chest of the storage of Matteo" };
DATA[DATA.length] = { id: "ruestung_14",	pic: "screens/ruestungen/bauernkleidung_1.jpg",					name: "Farmer's Clothing",				p_edge: 15,		p_point: 15,	p_fire: 0,		p_magic: 0,		value: 80,		note: "You will get this one at Lobart's farm (quest <b>'Lobart's work clothes'</b>)." };
DATA[DATA.length] = { id: "ruestung_15",	pic: "screens/ruestungen/lederruestung.jpg",					name: "Leather Armor",					p_edge: 25,		p_point: 25,	p_fire: 0,		p_magic: 0,		value: 250,		note: "You can buy it from <b>Matteo</b>, one of the teachers in Khorinis. Furthermore you can get it from <b>Orlan</b>, the landlord of the tavern.<br><nobr><li>No longer offers any Dragon fire protection.</li></nobr>" };
DATA[DATA.length] = { id: "ruestung_16",	pic: "screens/ruestungen/ruestung_aus_crawlerplatten.jpg",		name: "Crawler Plate Armor",			p_edge: 55,		p_point: 55,	p_fire: 20,		p_magic: 15,	value: 1500,	note: "The Crawler Plate Armor will be manufactured by <b>Wolf</b>. <b>Gestath</b> will give you the hint for it. (quest <b>'The Crawler Armor'</b>) You need 10 minecrawler plates for it." };
DATA[DATA.length] = { id: "ruestung_17",	pic: "screens/ruestungen/ruestung_des_rings_des_wassers.jpg",	name: "Armor of the 'Ring of Water'",	p_edge: 40,		p_point: 40,	p_fire: 10,		p_magic: 10,	value: 1300,	note: "You get this armor at the meeting of the Ring of Water in <b>Orlan's Tavern</b> from Lares." };
DATA[DATA.length] = { id: "ruestung_18",	pic: "screens/ruestungen/piratenruestung.jpg",					name: "Pirate armor",					p_edge: 50,		p_point: 50,	p_fire: 0,		p_magic: 0,		value: 1300,	note: "<b>Greg</b> gives you the armor after he returns from Khorinis." };
DATA[DATA.length] = { id: "ruestung_19",	pic: "screens/ruestungen/mittlere_banditenruestung.jpg",		name: "Medium Bandit's Armor",			p_edge: 35,		p_point: 35,	p_fire: 0,		p_magic: 0,		value: 550,		note: "You can fetch this armor from <b>Bones</b> after you made the quest <b>'Razor hunt'</b>." };
DATA[DATA.length] = { id: "ruestung_20",	pic: "screens/ruestungen/schwere_banditenruestung.jpg",			name: "Heavy Bandit's Armor",			p_edge: 45,		p_point: 45,	p_fire: 0,		p_magic: 0,		value: 2100,	note: "You can buy it from <b>Huno</b> in the bandit's camp. When you make the quest <b>'A package of lock	picks'</b> for <b>Fisk</b> you will get the armor cheaper from him." };

DATA[DATA.length] = { section: "Armors which you can't get in the game" };
DATA[DATA.length] = { id: "ruestung_21",	pic: "screens/ruestungen/ruestung_von_ravens_garde.jpg",		name: "Armor of Raven's guard",			p_edge: 60,		p_point: 60,	p_fire: 0,		p_magic: 0,		value: 1300,	note: "<b>Thorus</b> and some temple guard in the bandits' camp wear this armor." };
DATA[DATA.length] = { id: "ruestung_49",	pic: "screens/ruestungen/bloodwyn_ruestung.jpg",				name: "Bloodwyn's Armor",				p_edge: 60,		p_point: 60,	p_fire: 0,		p_magic: 0,		value: 1300,	note: "<b>Ramon</b>, <b>Garaz</b> and the guards in the bandits' camp wear this armor." };
DATA[DATA.length] = { id: "ruestung_41",	pic: "screens/ruestungen/zerrissene_ruestung.jpg",				name: "Broken Armor",					p_edge: 0,		p_point: 0,		p_fire: 0,		p_magic: 0,		value: 1300,	note: "'Armor of the Ring of Water' without script." };
DATA[DATA.length] = { id: "ruestung_44",	pic: "screens/ruestungen/kapitaens_kleidung.jpg",				name: "Captain's clothes",				p_edge: 55,		p_point: 55,	p_fire: 0,		p_magic: 0,		value: 1500,	note: "<b>Greg's</b> armor." };
DATA[DATA.length] = { id: "ruestung_28",	pic: "screens/ruestungen/buergerin_kleidung_1.jpg",				name: "Citizen's Clothing 1",			p_edge: 10,		p_point: 10,	p_fire: 0,		p_magic: 0,		value: 0,		note: "Worn by some female citizens." };
DATA[DATA.length] = { id: "ruestung_29",	pic: "screens/ruestungen/buergerin_kleidung_2.jpg",				name: "Citizen's Clothing 2",			p_edge: 10,		p_point: 10,	p_fire: 0,		p_magic: 0,		value: 0,		note: "Worn by some female citizens." };
DATA[DATA.length] = { id: "ruestung_30",	pic: "screens/ruestungen/buergerin_kleidung_3.jpg",				name: "Citizen's Clothing 3",			p_edge: 10,		p_point: 10,	p_fire: 0,		p_magic: 0,		value: 0,		note: "Worn by some female citizens." };
DATA[DATA.length] = { id: "ruestung_37",	pic: "screens/ruestungen/straeflings_kleidung.jpg",				name: "Convict's Clothing",				p_edge: 20,		p_point: 20,	p_fire: 0,		p_magic: 0,		value: 10,		note: "This armor is worn by some former prisoners." };
DATA[DATA.length] = { id: "ruestung_38",	pic: "screens/ruestungen/cor_angars_ruestung.jpg",				name: "Cor Angar's Armor",				p_edge: 70,		p_point: 70,	p_fire: 35,		p_magic: 0,		value: 600,		note: "The templar armor of <b>Angar</b>." };
DATA[DATA.length] = { id: "ruestung_51",	pic: "screens/ruestungen/dunkler_umhang.jpg",					name: "Dark Cloak",						p_edge: 15,		p_point: 40,	p_fire: 15,		p_magic: 15,	value: 500,		note: "Worn by Seekers." };
DATA[DATA.length] = { id: "ruestung_39",	pic: "screens/ruestungen/diegos_ruestung.jpg",					name: "Diego's Armor",					p_edge: 30,		p_point: 30,	p_fire: 0,		p_magic: 0,		value: 450,		note: "Worn by <b>Diego</b> and other Shadows (<b>Scatty</b>, <b>Fisk</b>, <b>Dexter</b>)." };
DATA[DATA.length] = { id: "ruestung_25",	pic: "screens/ruestungen/bauernkleidung_2.jpg",					name: "Farmer's Clothing 2",			p_edge: 15,		p_point: 15,	p_fire: 0,		p_magic: 0,		value: 100,		note: "Worn by some farmers." };
DATA[DATA.length] = { id: "ruestung_26",	pic: "screens/ruestungen/baeuerin_tracht_1.jpg",				name: "Farmer's Dress 1",				p_edge: 10,		p_point: 10,	p_fire: 0,		p_magic: 0,		value: 0,		note: "Worn by some female farmers." };
DATA[DATA.length] = { id: "ruestung_27",	pic: "screens/ruestungen/baeuerin_tracht_2.jpg",				name: "Farmer's Dress 2",				p_edge: 10,		p_point: 10,	p_fire: 0,		p_magic: 0,		value: 0,		note: "Worn by some female farmers." };
DATA[DATA.length] = { id: "ruestung_36",	pic: "screens/ruestungen/ruestung_einer_drachenjaegerin.jpg",	name: "Female Dragon Hunter's Armor",	p_edge: 60,		p_point: 60,	p_fire: 30,		p_magic: 0,		value: 0,		note: "There is no use for it in the game." };
DATA[DATA.length] = { id: "ruestung_31",	pic: "screens/ruestungen/wams_des_statthalters.jpg",			name: "Governor's Doublet",				p_edge: 40,		p_point: 40,	p_fire: 0,		p_magic: 0,		value: 1100,	note: "<b>Larius</b> wears this armor." };
DATA[DATA.length] = { id: "ruestung_34",	pic: "screens/ruestungen/richterrobe.jpg",						name: "Judge's Robe",					p_edge: 10,		p_point: 10,	p_fire: 0,		p_magic: 0,		value: 0,		note: "The <b>Judge</b> wears this robe." };
DATA[DATA.length] = { id: "ruestung_32",	pic: "screens/ruestungen/wirt_kleidung.jpg",					name: "Landlord's Clothing",			p_edge: 10,		p_point: 10,	p_fire: 0,		p_magic: 0,		value: 0,		note: "Most of the landlords wear this." };
DATA[DATA.length] = { id: "ruestung_40",	pic: "screens/ruestungen/lesters_robe.jpg",						name: "Lester's Robe",					p_edge: 25,		p_point: 25,	p_fire: 0,		p_magic: 0,		value: 300,		note: "<b>Lester</b> and <b>Fortuno</b> wear this armor of former novices." };
DATA[DATA.length] = { id: "ruestung_42",	pic: "screens/ruestungen/leichte_kdw.jpg",						name: "Light Cowl",						p_edge: 50,		p_point: 50,	p_fire: 25,		p_magic: 25,	value: 1300,	note: "Light Water Mage's Robe." };
DATA[DATA.length] = { id: "ruestung_50",	pic: "screens/ruestungen/magische_ruestung.jpg",				name: "Magic Armor",					p_edge: 100,	p_point: 100,	p_fire: 50,		p_magic: 50,	value: 15000,	note: "Armor with fire effects." };
DATA[DATA.length] = { id: "ruestung_48",	pic: "screens/ruestungen/alte_ruestung.jpg",					name: "Old Armor",						p_edge: 45,		p_point: 45,	p_fire: 45,		p_magic: 45,	value: 0,		note: "Looks like Raven's armor." };
DATA[DATA.length] = { id: "ruestung_52",	pic: "screens/ruestungen/alte_ritterruestung.jpg",				name: "Old Knight's Armor",				p_edge: 100,	p_point: 100,	p_fire: 50,		p_magic: 50,	value: 500,		note: "Armor of a Shadowlord." };
DATA[DATA.length] = { id: "ruestung_46",	pic: "screens/ruestungen/erzbaronruestung.jpg",					name: "Ore Baron Armor",				p_edge: 60,		p_point: 60,	p_fire: 0,		p_magic: 0,		value: 1300,	note: "Former Ore Barons wear this armor." };
DATA[DATA.length] = { id: "ruestung_45",	pic: "screens/ruestungen/piratenkleidung.jpg",					name: "Pirate clothes",					p_edge: 40,		p_point: 40,	p_fire: 0,		p_magic: 0,		value: 1100,	note: "All pirates who don't wear a Pirate Armor wear these Pirate clothes (<b>Skip</b>...)." };
DATA[DATA.length] = { id: "ruestung_47",	pic: "screens/ruestungen/ravens_ruestung.jpg",					name: "Raven's Armor",					p_edge: 70,		p_point: 70,	p_fire: 50,		p_magic: 50,	value: 1300,	note: "This armor is only worn by <b>Raven</b>, <b>Rhademes</b> and <b>Quarhodron</b>." };
DATA[DATA.length] = { id: "ruestung_35",	pic: "screens/ruestungen/robe_der_dunklen_kuenste.jpg",			name: "Robe of the Dark Arts",			p_edge: 100,	p_point: 100,	p_fire: 50,		p_magic: 50,	value: 15000,	note: "Worn by the demon summoner (<b>Xardas</b>)." };
DATA[DATA.length] = { id: "ruestung_33",	pic: "screens/ruestungen/schmied_kleidung.jpg",					name: "Smith's Clothing",				p_edge: 10,		p_point: 10,	p_fire: 0,		p_magic: 0,		value: 0,		note: "Every smith wears these clothes." };
DATA[DATA.length] = { id: "ruestung_43",	pic: "screens/ruestungen/wassermagierrobe.jpg",					name: "Water Mage's Robe",				p_edge: 80,		p_point: 80,	p_fire: 40,		p_magic: 40,	value: 450,		note: "All Water Mages wear this robe." };
