DATA[DATA.length] = {subtype: "comment", text:"For all recipes a laboratory flask (LWB) is needed in addition to the specified ingredients. If it is missing, the recipe isn´t brewed and the hero breaks off the alchemy action. Potions must be learned in a certain order. For example: first you learn Essence of Healing, then Extract of Healing, Elixir of Healing and only then you can learn the Elixir of Life or Pure Life Energy (from recipe)… if you ask the correct teacher (look at the teacher's guide). The same scheme works for mana potions. Elixirs of Strength and Dexterity do not need any previous knowledge. Depending on the quality of the potion you need more or less learning points. Each recipe shows the ingredients which you need to brew a potion when you are using the alchemy bench. Also exotic recipes, like new tobacco types can be brewed. Make sure that you carry all the ingredients in your inventory, otherwise you will hear \"I don't have the right item\" from the hero and you are surprised why it doesn't work!"};


DATA[DATA.length] = {section: "Herbs"};
DATA[DATA.length] = {id:"herb_1", pic:"screens/kraeuter/herb_2.jpg", name: "Blue Elder", effect:"regenerates 5 mana points and 5 life points", value:"10", text:"You can eat it. <br>- <a href=\"guide_trader_eng.htm?id=ware_109\">Merchants</a>"};
DATA[DATA.length] = {id:"herb_4", pic:"screens/kraeuter/herb_11.jpg", name: "Dark Mushroom", effect:"regenerates 5 life points", value:"10", text:"You get +5 to mana (permanent) every 50 mushrooms you eat. <br>- there are 553 mushrooms in the world (257 in Jharkendar, 128 in the Valley of Mines, 168 in Khorinis) <br>- <a href=\"guide_trader_eng.htm?id=ware_112\">Merchants</a>"};
DATA[DATA.length] = {id:"herb_2", pic:"screens/kraeuter/herb_12.jpg", name: "Digger Meat", effect:"regenerates 15 life points", value:"30", text:"You can eat it. <br>- there are 321 digger meats in the world (127 in Jharkendar, 96 in the Valley of Mines, 98 in Khorinis) <br>- <a href=\"guide_trader_eng.htm?id=ware_110\">Merchants</a>"};
DATA[DATA.length] = {id:"herb_14", pic:"screens/kraeuter/herb_14.jpg", name: "Dragonroot", effect:"+1 to strength (permanent)", value:"500", text:"It is needed for brewing Elixir of Strength. <br>- <a href=\"guide_trader_eng.htm?id=ware_111\">Merchants</a>"};
DATA[DATA.length] = {id:"herb_13", pic:"screens/kraeuter/herb_9.jpg", name: "Fireweed", effect:"regenerates 15 mana points", value:"20", text:"It is needed for brewing Mana Extract (alchemy). <br>- <a href=\"guide_trader_eng.htm?id=ware_115\">Merchants</a>"};
DATA[DATA.length] = {id:"herb_9", pic:"screens/kraeuter/herb_8.jpg", name: "Fire Nettle", effect:"regenerates 10 mana points", value:"10", text:"It is needed for brewing Mana Essence (alchemy). <br>- <a href=\"guide_trader_eng.htm?id=ware_116\">Merchants</a>"};
DATA[DATA.length] = {id:"herb_10", pic:"screens/kraeuter/herb_10.jpg", name: "Fire Root", effect:"regenerates 20 mana points", value:"40", text:"It is needed for brewing Mana Elixir (alchemy). <br>- <a href=\"guide_trader_eng.htm?id=ware_117\">Merchants</a>"};
DATA[DATA.length] = {id:"herb_3", pic:"screens/kraeuter/herb_3.jpg", name: "Goblin Berry", effect:"+1 to dexterity (permanent)", value:"250", text:"It is needed for brewing Elixir of Dexterity. <br>- <a href=\"guide_trader_eng.htm?id=ware_118\">Merchants</a>"};
DATA[DATA.length] = {id:"herb_11", pic:"screens/kraeuter/herb_6.jpg", name: "Healing Herb", effect:"regenerates 20 life points", value:"40", text:"It is needed for brewing Extract of Healing (alchemy). <br>- <a href=\"guide_trader_eng.htm?id=ware_119\">Merchants</a>"};
DATA[DATA.length] = {id:"herb_12", pic:"screens/kraeuter/herb_5.jpg", name: "Healing Plant", effect:"regenerates 10 life points", value:"20", text:"It is needed for brewing Essence of Healing (alchemy). <br>- <a href=\"guide_trader_eng.htm?id=ware_120\">Merchants</a>"};
DATA[DATA.length] = {id:"herb_7", pic:"screens/kraeuter/herb_7.jpg", name: "Healing Root", effect:"regenerates 30 life points", value:"60", text:"It is needed for brewing Elixir of Healing (alchemy). <br>- <a href=\"guide_trader_eng.htm?id=ware_121\">Merchants</a>"};
DATA[DATA.length] = {id:"herb_8", pic:"screens/kraeuter/herb_8.jpg", name: "King's Sorrel", effect:"regenerates 5 life points", value:"500", text:"It is needed for brewing potions with permanent effects. <br>- <a href=\"guide_trader_eng.htm?id=ware_122\">Merchants</a>"};
DATA[DATA.length] = {id:"herb_19", pic:"screens/kraeuter/herb_13.jpg", name: "Meadow Berry", effect:"regenerates 5 life points", value:"10", text:"You can eat it."};
DATA[DATA.length] = {id:"herb_16", pic:"screens/kraeuter/herb_16.jpg", name: "Meadow Knotweed", effect:"regenerates 5 life points", value:"100", text:"You need it to make healing and mana potions. <br>- <a href=\"guide_trader_eng.htm?id=ware_113\">Merchants</a>"};
DATA[DATA.length] = {id:"herb_15", pic:"screens/kraeuter/herb_8.jpg", name: "Snapperweed", effect:"<s>15</s> 60 seconds faster run", value:"100", text:"It is needed for brewing speed potions. <br>- <a href=\"guide_trader_eng.htm?id=ware_123\">Merchants</a>"};
DATA[DATA.length] = {id:"herb_5", pic:"screens/kraeuter/herb_14.jpg", name: "Sun Aloe", effect:"-", value:"500", text:"Can no longer be eaten."};
DATA[DATA.length] = {id:"herb_17", pic:"screens/kraeuter/herb_15.jpg", name: "Swampweed", effect:"If you eat 5 of them you get 'stoned' and time flows slower", value:"10", text:"If you know alchemy then you can use it to make joints. <br>- <a href=\"guide_trader_eng.htm?id=ware_126\">Merchants</a>"};
DATA[DATA.length] = {id:"herb_6", pic:"screens/kraeuter/herb_1.jpg", name: "Turnip", effect:"regenerates 2 life points", value:"3", text:"You can eat it. <br>- <a href=\"guide_trader_eng.htm?id=ware_114\">Merchants</a>"};
DATA[DATA.length] = {id:"herb_25", pic:"screens/kraeuter/unkraut.jpg", name: "Weed", effect:"no effect", value:"-", text:"You can eat it. You can find it in the monastery and in the Valley of Mines."};
DATA[DATA.length] = {id:"herb_18", pic:"screens/kraeuter/herb_4.jpg", name: "Woodland Berry", effect:"regenerates 5 life points", value:"10", text:"You can eat it. <br>- <a href=\"guide_trader_eng.htm?id=ware_127\">Merchants</a>"};

DATA[DATA.length] = {section: "Potions<br>(you can brew)"};
DATA[DATA.length] = {id:"alc_1", pic: "screens/trank/tr_03.jpg", name: "Essence of Healing", effect:"heals 50 life points", value:"25", text:"Ingredients: 2 Healing Plants, 1 Meadow Knotweed, 1 Lab Water Bottle (LWB). Teachers: <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_36>Ignaz</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_18>Constantino</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_169>Neoras</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_462>Riordian</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_95>Sagitta</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_314>Vatras</a> (look at the teacher's guide: alchemy)<br><br>Condition: nothing, Learning points: 1"};
DATA[DATA.length] = {id:"alc_2", pic:"screens/trank/tr_04.jpg", name: "Extract of Healing", effect:"heals 70 life points", value:"35", text:"Ingredients: 2 Healing Herbs, 1 Meadow Knotweed, 1 LWB. Teachers: <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_18>Constantino</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_169>Neoras</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_462>Riordian</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_95>Sagitta</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_314>Vatras</a> (look at the teacher's guide: alchemy)<br><br>Condition: Essence of Healing, Learning points: 3"};
DATA[DATA.length] = {id:"alc_3", pic:"screens/trank/tr_05.jpg", name: "Elixir of Healing", effect:"heals 100 life points", value:"50", text:"Ingredients: 2 Healing Roots, 1 Meadow Knotweed, 1 LWB. Teachers: <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_18>Constantino</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_169>Neoras</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_314>Vatras</a> (look at the teacher's guide: alchemy)<br><br>Condition: Extract of Healing, Learning points: 5"};
DATA[DATA.length] = {id:"alc_4", pic:"screens/trank/tr_10.jpg", name: "Elixir of Life", effect:"+20 to life points (permanent)", value:"1500", text:"Ingredients: 1 Healing Root, 1 King's Sorrel, 1 LWB. Teachers: <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_18>Constantino</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_169>Neoras</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_314>Vatras</a> (look at the teacher's guide: alchemy)<br><br>Condition: Elixir of Healing, Learning points: 10"};
DATA[DATA.length] = {id:"alc_14", pic:"screens/trank/tr_05.jpg", name: "Pure Life Energy", effect:"complete healing", value:"300", text:"Ingredients: 3 Essences of Healing, 1 Meadow Knotweed. Teacher: none (it can only be learned from recipes)<br><br>Condition: Elixir of Healing, Learning points: none"};
DATA[DATA.length] = {id:"alc_5", pic:"screens/trank/tr_06.jpg", name: "Mana Essence", effect:"regenerates 50 mana points", value:"25", text:"Ingredients: 2 Fire Nettles, 1 Meadow Knotweed, 1 LWB. Teachers: <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_36>Ignaz</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_18>Constantino</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_169>Neoras</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_462>Riordian</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_95>Sagitta</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_314>Vatras</a> (look at the teacher's guide: alchemy)<br><br>Condition: nothing, Learning points: 1"};
DATA[DATA.length] = {id:"alc_6", pic:"screens/trank/tr_07.jpg", name: "Mana Extract", effect:"regenerates 75 mana points", value:"40", text:"Ingredients: 2 Fireweeds, 1 Meadow Knotweed, 1 LWB. Teachers: <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_18>Constantino</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_169>Neoras</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_95>Sagitta</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_462>Riordian</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_314>Vatras</a> (look at the teacher's guide: alchemy)<br><br>Condition: Mana Essence, Learning points: 3"};
DATA[DATA.length] = {id:"alc_7", pic:"screens/trank/tr_08.jpg", name: "Mana Elixir", effect:"regenerates 100 mana points", value:"60", text:"Ingredients: 2 Fire Roots, 1 Meadow Knotweed, 1 LWB. Teachers: <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_169>Neoras</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_462>Riordian</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_95>Sagitta</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_314>Vatras</a> (look at the teacher's guide: alchemy)<br><br>Condition: Mana Extract, Learning points: 5"};
DATA[DATA.length] = {id:"alc_15", pic:"screens/trank/tr_08.jpg", name: "Pure Mana", effect:"complete regeneration of mana", value:"500", text:"Ingredients: 3 Mana Essences, 1 Meadow Knotweed. Teachers: none (it can only be learned from recipes)<br><br>Condition: Mana Elixir, Learning points: none"};
DATA[DATA.length] = {id:"alc_8", pic:"screens/trank/tr_11.jpg", name: "Elixir of Spirit", effect:"+5 to mana points (permanent)", value:"1500", text:"Ingredients: 1 Fire Root, 1 King's Sorrel, 1 LWB. Teachers: <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_169>Neoras</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_462>Riordian</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_95>Sagitta</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_314>Vatras</a> (look at the teacher's guide: alchemy)<br><br>Condition: Mana Elixir, Learning points: 10"};
DATA[DATA.length] = {id:"alc_9", pic:"screens/trank/tr_01.jpg", name: "Elixir of Strength", effect:"+3 to strength (permanent)", value:"800", text:"Ingredients: 1 Dragonroot, 1 King's Sorrel, 1 LWB. Teachers: <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_18>Constantino</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_314>Vatras</a> (look at the teacher's guide: alchemy)<br><br>Condition: none, Learning points: 20"};
DATA[DATA.length] = {id:"alc_10", pic:"screens/trank/tr_09.jpg", name: "Elixir of Dexterity", effect:"+3 to dexterity (permanent)", value:"800", text:"Ingredients: 1 Goblin Berry, 1 King's Sorrel, 1 LWB. Teachers: <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_462>Riordian</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_95>Sagitta</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_314>Vatras</a> (look at the teacher's guide: alchemy)<br><br>Condition: none, Learning points: 20"};
DATA[DATA.length] = {id:"alc_16", pic:"screens/trank/tr_01.jpg", name: "Potion of mental alteration", effect:"250 experience points per chapter", value:"300", text:"Ingredients: Essence of Healing, Mana Extract, 2 Bloodfly stinger, red Tear-Pepper, 1 LWB. Teacher: none (you get the recipe from <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_502>Miguel</a> in front of the bandits camp - Quest <a href=content_quest_eng.htm?data=data_quest_eng.js&id=q_188>'Mental meanders'</a>)<br><br>Condition: Ability to 'Take secretion from bloodfly sting', Learning points: none"};
DATA[DATA.length] = {id:"alc_11", pic:"screens/trank/tr_12.jpg", name: "Speed Potion", effect:"temporarily boosts speed (5 minutes)", value:"200", text:"Ingredients: 1 Snapperweed, 1 Meadow Knotweed, 1 LWB. Teachers: <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_36>Ignaz</a>, <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_314>Vatras</a> (look at the teacher's guide: alchemy)<br><br>Conditions: none, Learning points: 5"};
DATA[DATA.length] = {id:"alc_12", pic:"screens/trank/tr_11.jpg", name: "Embarla Firgasto", effect:"+15 to strength or dexterity (permanent), depending on which attribute is higher", value:"1500", text:"Ingredients: 10 Dragon Eggs, 1 Black Pearl, 1 Sulfur, 1 LWB. You learn it from a recipe which you find on Irodrath."};

DATA[DATA.length] = {section: "Special Potions<br>(you can not brew)"};
DATA[DATA.length] = {id:"alc_18", pic:"screens/trank/tr_11.jpg", name: "Essence of Spirit", effect:"+3 to mana points (permanent)", value:"150", text:"You can find it on a shelf in the right wing of the <a href=content_orte_eng.htm?data=data_orte_eng.js&id=o_153>great library</a> of Jharkendar."};
DATA[DATA.length] = {id:"alc_13", pic:"screens/trank/tr_01.jpg", name: "Dragon Egg Potion", effect:"+5 to strength (permanent)", value:"50", text:"You get it when you bring a dragon egg (found in the treasure of the Ice-Dragon) to <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_169>Neoras</a>."};
DATA[DATA.length] = {id:"alc_20", pic:"screens/trank/tr_14.jpg", name: "Healing of Addiction", effect:"heals 50 life points", value:"25", text:"You get it from <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_95>Sagitta</a>, when you have got the order from <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_150>Randolph</a> to bring him his medicine. (Quest <a href=content_quest_eng.htm?data=data_quest_eng.js&id=q_64>'Deprivation'</a>)"};
DATA[DATA.length] = {id:"alc_19", pic:"screens/trank/tr_14.jpg", name: "Healing of Possession", effect:"heals 50 life points / heals possession", value:"25", text:"You can get it from <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_173>Pyrokar</a> if you pay for it."};
DATA[DATA.length] = {id:"alc_21", pic:"screens/trank/tr_14.jpg", name: "Healing of the Black Fever", effect:"heals 50 life points", value:"25", text:"You will get it from <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_75>Vatras</a> for <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_152>Hilda</a> (Quest <a href=content_quest_eng.htm?data=data_quest_eng.js&id=q_45>'Healing for Hilda'</a>)."};
DATA[DATA.length] = {id:"alc_17", pic:"screens/trank/tr_14.jpg", name: "Tears of Innos", effect:"complete healing / +5 Strength (permanent) / +5 Dexterity (permanent) / 5 minutes speed boost", value:"10", text:"You will find it in the <a href=content_orte_eng.htm?data=data_orte_eng.js&id=o_66>secret library</a> in the cellar of the monastery.<br>Attention: Only Mages can drink it!"};

DATA[DATA.length] = {section: "Other Ingredients/Recipes"};
DATA[DATA.length] = {id:"herb_20", pic:"screens/kraeuter/tabak.jpg", name: "Honey tobacco", effect:"---", value:"10", text:"Ingredients: 1 Honey, 1 Apple tobacco, 1 Lab Water Bottle <br><a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_1>Abuyin</a> wants to have honey tobacco and will buy it for 10 gold."};
DATA[DATA.length] = {id:"herb_22", pic:"screens/kraeuter/tabak.jpg", name: "Shroom tobacco", effect:"---", value:"10", text:"Ingredients: 1 Dark mushroom, 1 Apple tobacco, 1 Lab Water Bottle <br>You should give it to <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_108>Dar</a>. It´s funny."};
DATA[DATA.length] = {id:"herb_21", pic:"screens/kraeuter/tabak.jpg", name: "Weed tobacco", effect:"---", value:"10", text:"Ingredients: 1 Swampweed, 1 Apple tobacco, 1 Lab Water Bottle <br>The <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_27>gardener</a> smokes this tobacco."};
DATA[DATA.length] = {id:"herb_24", pic:"screens/kraeuter/sumpfkrautstengel.jpg", name: "Green novice", effect:"+5 ep when you smoke it the first time", value:"-", text:"Ingredients: 2 Swampweed, 1 Meadow Knotweed, 1 Lab Water Bottle <br>You need the green novice for <a href=content_npc_eng.htm?data=data_npc_eng.js&id=n_509>Fortuno</a> for the quest <a href=content_quest_eng.htm?data=data_quest_eng.js&id=q_188>'Mental Meanders'</a>."};
DATA[DATA.length] = {id:"herb_23", pic:"screens/kraeuter/sumpfkrautstengel.jpg", name: "Swampweed reefers", effect:"you get 'stoned' and time flows slower", value:"10", text:"Ingredients: 1 Swampweed, 1 Lab Water Bottle <br>You need to know how to handle swampweed to blend swampweed reefers."};