
DATA[DATA.length] = { section: "Runes 1st Circle of Magic" };
DATA[DATA.length] = { id: "rune_22",	pic: "screens/runen/rn41.jpg",				pic2: "screens/runen/zb_06.jpg",			name: "Fire Arrow",				mana: 5,					value: 500,		value2: 25,			effect: "Damage: 30",															trainer: "<b>Hyglas</b>, <b>Nefarius</b>",									ingred: "Sulfur",																	LP: "5",	note: "1)near <b>Juan</b> in Jharkendar<br><li>Half damage is dealt over 4 seconds.</li>" };
DATA[DATA.length] = { id: "rune_24",	pic: "screens/runen/rn35.jpg",				pic2: "screens/runen/zb_11.jpg",			name: "Ice Arrow",				mana: 7,					value: 500,		value2: 25,			effect: "Damage: 40",															trainer: "<b>Marduk</b>, <b>Nefarius</b>",									ingred: "Glacier Quartz",															LP: "5",	note: "1)at the stone circle where Angar lost his amulet, <b>beside the barrel</b> guarded by skeletons<br><li>Moved from Circle 2 to Circle 1.</li>" };
DATA[DATA.length] = { id: "rune_18",	pic: "screens/runen/rn47.jpg",				pic2: "screens/runen/zb_49.jpg",			name: "Small Lightning",		mana: 6,					value: 500,		value2: 60,			effect: "Damage: 30",															trainer: "<b>Marduk</b>, <b>Nefarius</b>",									ingred: "Rock Chrystal",															LP: "3",	note: "<li>Staggers living targets.</li>" };
DATA[DATA.length] = { id: "rune_21",	pic: "screens/runen/rn30.jpg",				pic2: "screens/runen/zb_16.jpg",			name: "Heal Light Wounds",		mana: 10,					value: 500,		value2: 25,			effect: "Heals: 50",															trainer: "<b>Parlan</b>, <b>Nefarius</b>",									ingred: "Healing Plant",															LP: "3",	note: "1)orc camp in Khorinis near pass to the Valley of Mines" };
DATA[DATA.length] = { id: "rune_25",	pic: "screens/runen/rn10.jpg",				pic2: "screens/runen/zb_34.jpg",			name: "Summon Wolf",			mana: 40,					value: 500,		value2: 75,			effect: "Summon: Wolf<br>Charged summon: Black Wolf",							trainer: "<b>Karras</b>, <b>Nefarius</b>",									ingred: "Wolf Skin",																LP: "5",	note: "<li>Moved from Circle 2 to Circle 1.</li>" };
DATA[DATA.length] = { id: "rune_20",	pic: "screens/runen/rn31.jpg",				pic2: "screens/runen/zb_15.jpg",			name: "Light",					mana: 10,					value: 500,		value2: 10,			effect: "",																		trainer: "<b>Parlan</b>, <b>Nefarius</b>",									ingred: "gold piece",																LP: "1",	note: "- Duration: 5 minutes<li>Tracks player much more accurately.</li><li>Effect brightness reduced to 40% without affecting illuminance.</li>" };

DATA[DATA.length] = { section: "Runes 2nd Circle of Magic" };
DATA[DATA.length] = { id: "rune_23",	pic: "screens/runen/rn32.jpg",				pic2: "screens/runen/zb_14.jpg",			name: "Fireball",				mana: 10,					value: 1000,	value2: 50,		effect: "Damage: 60",																trainer: "<b>Hyglas</b>, <b>Nefarius</b>, <b>Milten</b>",					ingred: "Pitch",																	LP: "10",	note: "<li>Half damage is dealt over 4 seconds.</li>" };
DATA[DATA.length] = { id: "rune_49",	pic: "screens/runen/ru_eislanze.jpg",		pic2: "screens/runen/sc_eislanze.jpg",		name: "Ice Lance",				mana: 15,					value: 1000,	value2: 100,	effect: "Damage: 75",																trainer: "<b>Marduk</b>, <b>Nefarius</b>, <b>Milten</b>",					ingred: "Glacier Quartz",															LP: "5",	note: "" };
DATA[DATA.length] = { id: "rune_new_3",	pic: "screens/runen/_rn_adanosball.jpg",	pic2: "screens/runen/_sc_adanosball.jpg",	name: "Lightning Bolt",			mana: 20,					value: 1000,	value2: 150,	effect: "Damage: 60",																trainer: "<b></b>",															ingred: "",																			LP: "5",	note: "<li>Stuns enemies, undead for twice as long.</li>" };
DATA[DATA.length] = { id: "rune_26",	pic: "screens/runen/rn48.jpg",				pic2: "screens/runen/zb_48.jpg",			name: "Wind Fist",				mana: 5, maxlevel: 4,		value: 1000,	value2: 60,		effect: "Damage: 15 per tier (max 60)",												trainer: "<b>Parlan</b>, <b>Nefarius</b>, <b>Milten</b>",					ingred: "Coal",																		LP: "5",	note: "<li>Deals magic instead of blunt damage.</li><li>Charge time 400ms per tier.</li>" };
DATA[DATA.length] = { id: "rune_19",	pic: "screens/runen/rn13.jpg",				pic2: "screens/runen/zb_31.jpg",			name: "Summon Goblin Skeleton",	mana: 20,					value: 1000,	value2: 75,		effect: "Summon: Lesser Goblin Skeleton<br>Charged summon: Goblin Skeleton",		trainer: "<b>Karras</b>, <b>Nefarius</b>",									ingred: "Goblin\'s Bone",															LP: "5",	note: "1)in Xardas’ chest in <b>Sekob’s House</b> at <b>Sekob's Farm</b><br><li>Moved from Circle 1 to Circle 2.</li>" };
DATA[DATA.length] = { id: "rune_51",	pic: "screens/runen/ru_windhose.jpg",		pic2: "screens/runen/sc_windhose.jpg",		name: "Dust Devil",				mana: 30,					value: 1000,	value2: 200,	effect: "Target is lifted by the devil and is knocked out.",						trainer: "<b>Nefarius</b>",													ingred: "Wings of a bloodfly",														LP: "5",	note: "- Duration: 10 seconds" };
//DATA[DATA.length] = { id: "rune_27",	pic: "screens/runen/rn15.jpg",				pic2: "screens/runen/zb_29.jpg",			name: "Sleep",					mana: 30,					value: 1000,	value2: 100,	effect: "Target human is put to sleep.",											trainer: "<b>Parlan</b>, <b>Nefarius</b>",									ingred: "Swampweed",																LP: "5",	note: "- Duration: 30 seconds<br><li>Now affects Cornelius, Judge and Larius.</li><li>Magicians in the city are now immune.</li><li>Player is never immune.</li>" };

DATA[DATA.length] = { section: "Runes 3rd Circle of Magic" };
DATA[DATA.length] = { id: "rune_29",	pic: "screens/runen/rn38.jpg",				pic2: "screens/runen/zb_08.jpg",			name: "Small Firestorm",		mana: 20,					value: 1500,	value2: 100,	effect: "Damage: 60, small area of effect",											trainer: "<b>Hyglas</b>, <b>Nefarius</b>",									ingred: "Pitch, Sulfur",															LP: "15",	note: "<li>Half damage is dealt over 4 seconds.</li>" };
DATA[DATA.length] = { id: "rune_32",	pic: "screens/runen/rn34.jpg",				pic2: "screens/runen/zb_12.jpg",			name: "Ice Block",				mana: 20,					value: 1500,	value2: 100,	effect: "Damage: 80",																trainer: "<b>Marduk</b>, <b>Nefarius</b>",									ingred: "Glacier Quartz, Aquamarine",												LP: "10",	note: "<li>All of the damage is dealt at 8 per second.</li><li>Freezes enemies while dealing damage over time.</li><li>Does not freeze large creatures.</li><li>Does not leave magic runes on corpses.</li>" };
DATA[DATA.length] = { id: "rune_33",	pic: "screens/runen/rn_kugelblitz.jpg",		pic2: "screens/runen/zb_35.jpg",			name: "Ball Lightning",			mana: 10, maxlevel: 4,		value: 1500,	value2: 75,		effect: "Damage: 30 per tier (max 120)",											trainer: "<b>Marduk</b>, <b>Nefarius</b>",									ingred: "Rock Chrystal, Sulfur",													LP: "10",	note: "<li>Staggers living targets.</li><li>Charge time 600ms per tier.</li>" };
DATA[DATA.length] = { id: "rune_53",	pic: "screens/runen/ru_geysir.jpg",			pic2: "screens/runen/sc_geysir.jpg",		name: "Water Geyser",			mana: 20,					value: 1500,	value2: 50,		effect: "Damage: 75; stun",															trainer: "<b>Nefarius</b>",													ingred: "Aquamarine",																LP: "10",	note: "<li>Instant.</li><li>Has a new more appropriate animation.</li>" };
DATA[DATA.length] = { id: "rune_28",	pic: "screens/runen/rn26.jpg",				pic2: "screens/runen/zb_19.jpg",			name: "Heal Medium Wounds",		mana: 20,					value: 1500,	value2: 60,		effect: "Heals: 100",																trainer: "<b>Parlan</b>, <b>Nefarius</b>",									ingred: "Healing Herb",																LP: "5",	note: "1)in mine at canyon in Jharkendar" };
DATA[DATA.length] = { id: "rune_30",	pic: "screens/runen/rn11.jpg",				pic2: "screens/runen/zb_33.jpg",			name: "Summon Skeleton",		mana: 60,					value: 1500,	value2: 75,		effect: "Summon: Lesser Skeleton<br>Charged summon: Skeleton",						trainer: "<b>Karras</b>, <b>Nefarius</b>",									ingred: "Skeleton\'s Bone",															LP: "10",	note: "" };
//DATA[DATA.length] = { id: "rune_31",	pic: "screens/runen/rn43.jpg",				pic2: "screens/runen/zb_05.jpg",			name: "Fear",					mana: 50,					value: 1500,	value2: 75,		effect: "Creatures flee away from you",												trainer: "<b>Parlan</b>, <b>Nefarius</b>",									ingred: "Black Pearl",																LP: "5",	note: "1)in the cave under <b>Hosh Pak's</b> place <br>2)in the old tower of Xardas on the upper floor.<li>Animals react immediately.</li><li>Can be used without a target.</li><li>No longer can bypasses immunity of magicians, paladins, golems, dragons and trolls.</li>" };

DATA[DATA.length] = { section: "Runes 4th Circle of Magic" };
DATA[DATA.length] = { id: "rune_37",	pic: "screens/runen/rn44.jpg",				pic2: "screens/runen/zb_03.jpg",			name: "Large Fireball",			mana: 20, maxlevel: 4,		value: 2000,	value2: 300,	effect: "Damage: 60 per tier (max 240)",											trainer: "<b>Hyglas</b>, <b>Nefarius</b>, <b>Milten</b>",					ingred: "Sulfur, Pitch",															LP: "10",	note: "<li>Half damage is dealt over 4 seconds.</li><li>Charge time 800ms per tier.</li>" };
DATA[DATA.length] = { id: "rune_54",	pic: "screens/runen/ru_unwetter.jpg",		pic2: "screens/runen/sc_unwetter.jpg",		name: "Ice Storm",				mana: 50,					value: 2000,	value2: 200,	effect: "Damage: 200, large area of effect",										trainer: "<b>Nefarius</b>",													ingred: "Glacier Quartz, Wings of a bloodfly",										LP: "5",	note: "<li>Moved from Circle 3 to Circle 4.</li><li>Renamed from Storm to Ice Storm for clarity.</li>" };
DATA[DATA.length] = { id: "rune_34",	pic: "screens/runen/rn29.jpg",				pic2: "screens/runen/zb_17.jpg",			name: "Lightning",				mana: 30,					value: 2000,	value2: 125,	effect: "Damage: 150",																trainer: "<b>Marduk</b>, <b>Nefarius</b>, <b>Milten</b>",					ingred: "Rock Crystal, Glacier Quartz",												LP: "15",	note: "<li>Staggers living targets.</li><li>Instant.</li><li>Changed animation to a more appropriate one.</li>" };
DATA[DATA.length] = { id: "rune_57",	pic: "screens/runen/ru_wasserfaust.jpg",	pic2: "screens/runen/sc_wasserfaust.jpg",	name: "Waterfist",				mana: 25,					value: 2000,	value2: 100,	effect: "Damage: 100; stun",														trainer: "<b>Nefarius</b>",													ingred: "Aquamarine, Rock Crystal",													LP: "10",	note: "" };
DATA[DATA.length] = { id: "rune_35",	pic: "screens/runen/rn12.jpg",				pic2: "screens/runen/zb_32.jpg",			name: "Summon Stone Golem",		mana: 80,					value: 2000,	value2: 150,	effect: "Summon: Stone Golem<br>Charged summon: Magic Golem",						trainer: "<b>Karras</b>, <b>Nefarius</b>, <b>Milten</b>",					ingred: "Heart of a Stone Golem",													LP: "15",	note: "" };
DATA[DATA.length] = { id: "rune_36",	pic: "screens/runen/rn36.jpg",				pic2: "screens/runen/zb_10.jpg",			name: "Destroy Undead",			mana: 20, maxlevel: 6,		value: 2000,	value2: 100,	effect: "Damage: 75 per tier (max 450)",											trainer: "<b>Parlan</b>, <b>Nefarius</b>, <b>Milten</b>",					ingred: "Holy Water",																LP: "10",	note: "<li>Deals no damage unless fatal.</li><li>Only affects undead.</li><li>Charge time 600ms per tier.</li>" };
DATA[DATA.length] = { id: "rune_new_4",	pic: "screens/runen/_rn_cage.jpg",			pic2: "screens/runen/_sc_cage.jpg",			name: "MagicCage",				mana: 60,					value: 3000,	value2: 250,	effect: "",							trainer: "<b></b>",	ingred: "",											LP: "",	note: "" };

DATA[DATA.length] = { section: "Runes 5th Circle of Magic" };
DATA[DATA.length] = { id: "rune_38",	pic: "screens/runen/rn17.jpg",				pic2: "screens/runen/zb_27.jpg",			name: "Large Firestorm",		mana: 30, maxlevel: 4,		value: 2500,	value2: 150,	effect: "Damage: 60 per tier (max 240), small area of effect",						trainer: "<b>Hyglas</b>, <b>Nefarius</b>, <b>Milten</b>",					ingred: "Sulfur, Tongue of Fire",													LP: "10",	note: "<li>Half damage is dealt over 4 seconds.</li><li>Charge time 1000ms per tier.</li>" };
DATA[DATA.length] = { id: "rune_39",	pic: "screens/runen/rn33.jpg",				pic2: "screens/runen/zb_13.jpg",			name: "Ice Wave",				mana: 60,					value: 2500,	value2: 200,	effect: "Damage: 80",																trainer: "<b>Marduk</b>, <b>Nefarius</b>, <b>Milten</b>",					ingred: "Glacier Quartz, Aquamarine",												LP: "20",	note: "<li>All of the damage is dealt at 8 per second.</li><li>Freezes enemies while dealing damage over time.</li><li>Does not freeze large creatures.</li><li>Does not leave magic runes on corpses.</li>" };
DATA[DATA.length] = { id: "rune_41",	pic: "screens/runen/rn37.jpg",				pic2: "screens/runen/zb_09.jpg",			name: "Heal Heavy Wounds",		mana: 40,					value: 2500,	value2: 200,	effect: "Heals: 200",																trainer: "<b>Parlan</b>, <b>Nefarius</b>, <b>Milten</b>",					ingred: "Healing Root",																LP: "10",	note: "" };
DATA[DATA.length] = { id: "rune_40",	pic: "screens/runen/rn14.jpg",				pic2: "screens/runen/zb_30.jpg",			name: "Summon Demon",			mana: 120,					value: 2500,	value2: 200,	effect: "Summon: Demon<br>Charged summon: Demon Lord",								trainer: "<b>Karras</b>, <b>Nefarius</b>, <b>Milten</b>",					ingred: "Heart of a Demon",															LP: "20",	note: "" };
DATA[DATA.length] = { id: "rune_46",	pic: "screens/runen/rn16.jpg",				pic2: "screens/runen/zb_28.jpg",			name: "Shrink Monster",			mana: 100,					value: 2500,	value2: 200,	effect: "",																			trainer: "<b>Parlan</b>, <b>Nefarius</b>, <b>Milten</b>",					ingred: "Goblin\'s Bone, Troll Tusk",												LP: "20",	note: "<li>Moved from Circle 6 to Circle 5.</li><li>Reduces monster size, attributes and protection by 30%.</li><li>Removes knockback ability of enemies.</li><li>Shrinking takes 3 seconds instead of 5.</li><li>No longer makes monsters flee.</li><li>No longer overrides targets original scale.</li>" };

DATA[DATA.length] = { section: "Runes 6th Circle of Magic" };
DATA[DATA.length] = { id: "rune_42",	pic: "screens/runen/rn39.jpg",				pic2: "screens/runen/zb_07.jpg",			name: "Rain of Fire",			mana: 80,					value: 3000,	value2: 250,	effect: "Damage: 300, large area of effect",										trainer: "<b>Hyglas</b>, <b>Pyrokar</b>, <b>Nefarius</b>, <b>Milten</b>",	ingred: "Pitch, Sulfur, Tongue of Fire",											LP: "20",	note: "<li>All damage is dealt over 4 seconds.</li><li>Changed animation to a slower one.</li>" };
DATA[DATA.length] = { id: "rune_new_5",	pic: "screens/runen/_rn_explosion.jpg",		pic2: "screens/runen/_sc_explosion.jpg",	name: "Explosion",				mana: 50,					value: 3000,	value2: 250,	effect: "Damage: 160",				trainer: "<b></b>",	ingred: "",											LP: "",	note: "<li>Half damage is dealt over 4 seconds.</li>" };
DATA[DATA.length] = { id: "rune_45",	pic: "screens/runen/rn46.jpg",				pic2: "screens/runen/zb_01.jpg",			name: "Army of Darkness",		mana: 150,					value: 3000,	value2: 250,	effect: "Summons: 6 Skeletons",														trainer: "<b>Karras</b>, <b>Nefarius</b>, <b>Milten</b>",					ingred: "Skeleton\'s Bone, Black Pearl, Heart of a Stone Golem, Heart of a Demon",	LP: "20",	note: "" };
DATA[DATA.length] = { id: "rune_43",	pic: "screens/runen/rn45.jpg",				pic2: "screens/runen/zb_02.jpg",			name: "Breath of Death",		mana: 100,					value: 3000,	value2: 250,	effect: "Damage: 400",																trainer: "<b>Pyrokar</b>, <b>Nefarius</b>, <b>Milten</b>",					ingred: "Coal, Black Pearl",														LP: "20",	note: "<li>Deals no damage unless fatal.</li><li>Only affects the living.</li>" };
DATA[DATA.length] = { id: "rune_44",	pic: "screens/runen/rn28.jpg",				pic2: "screens/runen/zb_18.jpg",			name: "Wave of Death",			mana: 150,					value: 3000,	value2: 250,	effect: "Damage: 400, area of effect",												trainer: "<b>Pyrokar</b>, <b>Nefarius</b>, <b>Milten</b>",					ingred: "Skeleton\'s Bone, Black Pearl ",											LP: "20",	note: "<li>Deals no damage unless fatal.</li><li>Only affects the living.</li>" };
DATA[DATA.length] = { id: "rune_47",	pic: "screens/runen/rn27.jpg",															name: "Holy Missile",			mana: 60,					value: 3000,					effect: "Damage: 300",																trainer: "read <b>almanac</b> in secret library",							ingred: "Holy Water",																LP: "",		note: "" };

DATA[DATA.length] = { section: "Runes Xth Circle of Magic" };
DATA[DATA.length] = { id: "rune_new_2",	pic: "screens/runen/_rn_acid.jpg",			pic2: "screens/runen/_sc_acid.jpg",			name: "Acid",					mana: 60,					value: 3000,	value2: 250,	effect: "",							trainer: "<b></b>",	ingred: "",											LP: "",	note: "" };
DATA[DATA.length] = { id: "rune_new_6",	pic: "screens/runen/_rn_extricate.jpg",		pic2: "screens/runen/_sc_extricate.jpg",	name: "Extricate",				mana: 60,					value: 3000,	value2: 250,	effect: "",							trainer: "<b></b>",	ingred: "",											LP: "",	note: "" };
DATA[DATA.length] = { id: "rune_new_7",	pic: "screens/runen/_rn_healother.jpg",		pic2: "screens/runen/_sc_healother.jpg",	name: "HealOther",				mana: 60,					value: 3000,	value2: 250,	effect: "",							trainer: "<b></b>",	ingred: "",											LP: "",	note: "" };
DATA[DATA.length] = { id: "rune_new_8",	pic: "screens/runen/_rn_quake.jpg",			pic2: "screens/runen/_sc_quake.jpg",		name: "Quake",					mana: 60,					value: 3000,	value2: 250,	effect: "",							trainer: "<b></b>",	ingred: "",											LP: "",	note: "" };

DATA[DATA.length] = { section: "Beliar Spells" };
DATA[DATA.length] = { id: "rune_48",	pic: "screens/runen/ru_wurzelschlingen.jpg",											name: "Root Snare",				mana: 50,					value: 2500,					effect: "Roots grows up from the ground and hold the target.",						trainer: "pray at <b>Shrine of Beliar</b>",									note: "- Duration: 20 seconds<br><li>Does not work against golems or summoned demons.</li>" };
DATA[DATA.length] = { id: "rune_50",	pic: "screens/runen/ru_energie_stehlen.jpg",											name: "Steal Energy",			mana: 30,					value: 3500,					effect: "Target is suspended in air and drained of life<br>Damage: 100 per second",	trainer: "pray at <b>Shrine of Beliar</b>",									note: "- Duration: 9 seconds<br>- Hero heals for damage caused by the spell<br>- Does not drain below 1 life" };
DATA[DATA.length] = { id: "rune_55",	pic: "screens/runen/ru_beliars_zorn.jpg",												name: "Beliar's Wrath",			mana: 40,					value: 3500,					effect: "Damage: 160",																trainer: "pray at <b>Shrine of Beliar</b>",									note: "<li>Deals halved damage against evil targets.</li>" };
DATA[DATA.length] = { id: "rune_52",	pic: "screens/runen/ru_waechter_erschaffen.jpg",										name: "Summon Stone Sentinel",	mana: 60,					value: 2000,					effect: "Summon: Stone Sentinel<br>Charged summon: Stone Sentinel (large)",			trainer: "pray at <b>Shrine of Beliar</b>",									note: "" };
DATA[DATA.length] = { id: "rune_58",	pic: "screens/runen/ru_zombie_erschaffen.jpg",											name: "Summon Zombie",			mana: 80,					value: 2000,					effect: "Summon: Zombie<br>Charged summon: Zombie (armored)",						trainer: "pray at <b>Shrine of Beliar</b>",									note: "" };
DATA[DATA.length] = { id: "rune_56",	pic: "screens/runen/ru_insektenschwarm.jpg",											name: "Insect Swarm",			mana: 20,					value: 1500,					effect: "Target is distracted by a swarm of insects<br>Damage: 80 per second",		trainer: "pray at <b>Shrine of Beliar</b>",									note: "- Duration: 6 seconds<br>- Target is not damaged below 1 life" };
DATA[DATA.length] = { id: "rune_59",	pic: "screens/runen/ru_schrei_der_toten.jpg",											name: "Cry of the Dead",		mana: 250, 					value: 2000,					effect: "Damage: 666, small area of effect",										trainer: "pray at <b>Shrine of Beliar</b>",									note: "- Drains all mana when used. - Does not affect undead." };

DATA[DATA.length] = { section: "Paladin Spells" };
DATA[DATA.length] = { id: "rune_14",	pic: "screens/runen/rn22.jpg",	pic2: "screens/runen/zb_23.jpg",	name: "Holy Light",									mana: 10,					value: 500,		value2: 50,		effect: "light for 5 minutes ",														trainer: "<b>Albrecht</b>",								LP: "1",			note: "You can buy scrolls from <b>Martin</b> in chapter 1 (needs 5 mana).<br><b>Albrecht</b> gives you the rune when you become a Paladin.<li>Tracks player much more accurately.</li><li>Effect brightness reduced to 40% without affecting illuminance.</li>" };
DATA[DATA.length] = { id: "rune_13",	pic: "screens/runen/rn23.jpg",	pic2: "screens/runen/zb_22.jpg",	name: "Holy Arrow",									mana: 10,					value: 500,		value2: 200,	effect: "Damage: 100",																trainer: "<b>Albrecht</b>",								LP: "3",			note: "You can buy scrolls from <b>Martin</b> in chapter 1 (needs 5 mana).<br><b>Albrecht</b> teaches you the rune in chapter 3 when the Eye of Innos is repaired." };
DATA[DATA.length] = { id: "rune_11",	pic: "screens/runen/rn19.jpg",	pic2: "screens/runen/zb_26.jpg",	name: "Harm Evil",									mana: 30,					value: 2000,	value2: 600,	effect: "Damage: 300",																trainer: "<b>Albrecht</b>",								LP: "5",			note: "You can buy scrolls from <b>Martin</b> in chapter 2 (needs 5 mana).<br><b>Albrecht</b> teaches you the rune in chapter 5." };
DATA[DATA.length] = { id: "rune_12",	pic: "screens/runen/rn25.jpg",	pic2: "screens/runen/zb_20.jpg",	name: "Destroy Evil",								mana: 60,					value: 3000,	value2: 1000,	effect: "Damage: 600",																trainer: "",											LP: "10",			note: "You can buy scrolls from <b>Martin</b> in chapter 4 and 5 (needs 5 mana).<br>There is no rune anymore in the game." };
DATA[DATA.length] = { id: "rune_17",	pic: "screens/runen/rn21.jpg",	pic2: "screens/runen/zb_24.jpg",	name: "Lesser Healing",								mana: 10,					value: 500,		value2: 100,	effect: "75 Healing",																trainer: "<b>Albrecht</b>",								LP: "3",			note: "You can buy scrolls from <b>Martin</b> in chapter 1 (needs 5 mana).<br><b>Albrecht</b> teaches you the rune in chapter 3 when the Eye of Innos is repaired." };
DATA[DATA.length] = { id: "rune_16",	pic: "screens/runen/rn20.jpg",	pic2: "screens/runen/zb_25.jpg",	name: "Medium Healing",								mana: 25,					value: 2000,	value2: 400,	effect: "150 Healing",																trainer: "<b>Albrecht</b>",								LP: "5",			note: "You can buy scrolls from <b>Martin</b> in chapter 2 (needs 5 mana).<br><b>Albrecht</b> teaches you the rune in chapter 5." };
DATA[DATA.length] = { id: "rune_15",	pic: "screens/runen/rn24.jpg",	pic2: "screens/runen/zb_21.jpg",	name: "Greater Healing",							mana: 50,					value: 3000,	value2: 800,	effect: "300 Healing",																trainer: "",											LP: "10",			note: "You can buy scrolls from <b>Martin</b> in chapter 2 (needs 5 mana).<br>There is no rune anymore in the game." };

DATA[DATA.length] = { section: "Teleport Spells" };
DATA[DATA.length] = { id: "rune_1",		pic: "screens/runen/rn03.jpg",									teleport: "To Harbor City",												note: "From <b>Lord Hagen</b> in chapter 3." };
DATA[DATA.length] = { id: "rune_4",		pic: "screens/runen/rn09.jpg",									teleport: "To Landowner",												note: "From <b>Lee</b> in chapter 3." };
DATA[DATA.length] = { id: "rune_3",		pic: "screens/runen/rn08.jpg",									teleport: "To Monastery",												note: "From <b>Pyrokar</b> in chapter 3." };
DATA[DATA.length] = { id: "rune_6",		pic: "screens/runen/rn05.jpg",									teleport: "To Pass of Khorinis",										note: "From the <b>dead Paladin</b> at the pass of Khorinis in Chapter 3." };
DATA[DATA.length] = { id: "rune_2",		pic: "screens/runen/rn06.jpg",									teleport: "To Tavern",													note: "From <b>Orlan</b> in chapter 3 (costs 500 gold)." };
DATA[DATA.length] = { id: "rune_5",		pic: "screens/runen/rn40.jpg",									teleport: "To Xardas",													note: "From <b>Lester</b> in chapter 3." };
DATA[DATA.length] = { id: "rune_10",	pic: "screens/runen/rn18.jpg",									teleport: "to the Paladin\'s Armor (secret of the library)",			note: "Ingredients: holy water, instruction is in the almanac in the <b>secret library</b> (only as paladin)." };
DATA[DATA.length] = { id: "rune_9",		pic: "screens/runen/rn07.jpg",									teleport: "To Castle",													note: "<li>Can be found in a tree house in swamp dragons lair.</li>" };
DATA[DATA.length] = { id: "rune_7",		pic: "screens/runen/rn02.jpg",									teleport: "To Old Demon Tower",											note: "From the <b>old tower</b> of Xardas, on the upper floor." };
DATA[DATA.length] = { id: "rune_8",		pic: "screens/runen/rn04.jpg",									teleport: "To Valley of Mines Pass",									note: "<li>Can be found near the entrance to the ice dragon cave, up a path next to a corpse.</li>" };
DATA[DATA.length] = { id: "rolle_14",	pic2: "screens/runen/zb_50.jpg",								teleport: "to a hut on a hill (House of the Guardian's of Death)",		note: "Allows for easy exit from the area behind the broken bridge.<li>Can be found near the skeleton with the Magic Bow.</li>" };

DATA[DATA.length] = { section: "Transformation Spells" };
DATA[DATA.length] = { id: "rolle_9",	pic2: "screens/runen/zb_43.jpg",									name: "Transform into Sheep",			mana: 5,	value2: 25,		note: "Trader who sell it: <b>Ignaz</b> (chapter 1), <b>Cronos</b>, <b>Gorax</b>, <b>Isgaroth</b> and <b>Karras</b> (chapter 3)" };
DATA[DATA.length] = { id: "rolle_5",	pic2: "screens/runen/zb_39.jpg",									name: "Transform into Giant Rat",		mana: 10,	value2: 50,		note: "Trader who sell it: <b>Ignaz</b> (chapter 1), <b>Sagitta</b> (chapter 3) and <b>Karras</b> (chapter 2)" };
DATA[DATA.length] = { id: "rolle_7",	pic2: "screens/runen/zb_41.jpg",									name: "Transform into Scavenger",		mana: 20,	value2: 100,	note: "Trader who sell it: <b>Ignaz</b> (chapter 1), <b>Gorax</b>, <b>Cronos</b>, <b>Isgaroth</b>, <b>Karras</b> (chapter 3) and <b>Vatras</b> (in chapter 6)" };
DATA[DATA.length] = { id: "rolle_13",	pic2: "screens/runen/zb_47.jpg",									name: "Transform into Wolf",			mana: 30,	value2: 150,	note: "Trader who sell it: <b>Ignaz</b> (chapter 1), <b>Cronos</b>, <b>Gorax</b>, <b>Karras</b> (chapter 3) und <b>Isgaroth</b> (chapter 4); You also find 2 pieces of it in the chest M07 (monastery)." };
DATA[DATA.length] = { id: "rolle_4",	pic2: "screens/runen/zb_38.jpg",									name: "Transform into Field Raider",	mana: 30,	value2: 150,	note: "Trader who sell it: <b>Ignaz</b> (chapter 1), <b>Cronos</b> (chapter 3), <b>Gorax</b> (chapter 3), <b>Karras</b> (chapter 2) and <b>Isgaroth</b> (chapter 4)" };
DATA[DATA.length] = { id: "rolle_6",	pic2: "screens/runen/zb_40.jpg",									name: "Transform into Lurker",			mana: 40,	value2: 200,	note: "Trader who sell it: <b>Ignaz</b> (chapter 1), <b>Gorax</b>, <b>Cronos</b>, <b>Isgaroth</b> and <b>Karras</b> (chapter 5)" };
DATA[DATA.length] = { id: "rolle_11",	pic2: "screens/runen/zb_45.jpg",									name: "Transform into Lizard",			mana: 40,	value2: 200,	note: "Trader who sell it: <b>Ignaz</b> (chapter 1), <b>Sagitta</b> and <b>Karras</b> (chapter 3)" };
DATA[DATA.length] = { id: "rolle_10",	pic2: "screens/runen/zb_44.jpg",									name: "Transform into Snapper",			mana: 50,	value2: 250,	note: "Trader who sell it: <b>Ignaz</b> (chapter 1), <b>Karras</b> (chapter 3), <b>Cronos</b>, <b>Gorax</b> and <b>Isgaroth</b> (chapter 4)" };
DATA[DATA.length] = { id: "rolle_12",	pic2: "screens/runen/zb_46.jpg",									name: "Transform into Warg",			mana: 60,	value2: 300,	note: "Trader who sell it: <b>Ignaz</b> (chapter 1), <b>Cronos</b>, <b>Gorax</b>, <b>Isgaroth</b> and <b>Karras</b> (chapter 4)" };
DATA[DATA.length] = { id: "rolle_2",	pic2: "screens/runen/zb_36.jpg",									name: "Transform into Dragon Snapper",	mana: 70,	value2: 350,	note: "Trader who sell it: <b>Ignaz</b> (chapter 1), <b>Cronos</b>, <b>Isgaroth</b>, <b>Gorax</b> and <b>Karras</b> (chapter 5)" };
DATA[DATA.length] = { id: "rolle_3",	pic2: "screens/runen/zb_37.jpg",									name: "Transform into Fire Lizard",		mana: 80,	value2: 400,	note: "Trader who sell it: <b>Ignaz</b> (chapter 1), <b>Sagitta</b> and <b>Karras</b> (chapter 4)" };
DATA[DATA.length] = { id: "rolle_8",	pic2: "screens/runen/zb_42.jpg",									name: "Transform into Shadowbeast",		mana: 100,	value2: 500,	note: "Trader who sell it: <b>Ignaz</b> (chapter 1), <b>Sagitta</b> and <b>Karras</b> (chapter 5)" };

DATA[DATA.length] = { section: "Other Spells" };
DATA[DATA.length] = { id: "rolle_1",	pic2: "screens/runen/zb_04.jpg",									name: "Oblivion",						mana: 10,	value2: 100,	note: "Trader who sell it: <b>Ignaz</b> and <b>Lutero</b>; You also find 2 pieces of it in Chest K32 (<b>Zuris House</b>)<br><li>Reduced availability.</li><li>New model.</li>" };
DATA[DATA.length] = { id: "rune_27",	pic2: "screens/runen/zb_29.jpg",									name: "Sleep",							mana: 30,	value2: 100,	note: "Target is put to sleep for 30 seconds.<br><li>There is no rune available anymore.</li><li>Reduced availability.</li><li>Now affects most living animals as well, though few animals without proper animation are unaffected.</li><li>Now affects Cornelius, Judge and Larius.</li><li>Magicians in the city are now immune.</li><li>Player is now never immune.</li><li>Cannot target creatures beyond its range.</li>" };
DATA[DATA.length] = { id: "rune_new_1",	pic2: "screens/runen/_sc_rage.jpg",									name: "Rage",							mana: 60,	value2: 150,	note: "Forces the target to attack the nearest creature. Has same limitations as sleep, except the animation requirement.<li>There is no rune available.</li>" };
DATA[DATA.length] = { id: "rune_31",	pic2: "screens/runen/zb_05.jpg",									name: "Fear",							mana: 100,	value2: 200,	note: "Creatures flee away from you.<li>There is no rune available anymore.</li><li>Greatly reduced availability.</li><li>Animals react immediately.</li><li>Can be used without a target.</li><li>No longer can bypasses immunity of magicians, paladins, golems, dragons and trolls.</li>" };

DATA[DATA.length] = { section: "Blank Runes" }; //alle runenrohlinge bekommen die selbe id, naemlich "rune_rohling"
DATA[DATA.length] = { id: "rune_rohling",	rohling: "Quest: <b>'The Path of Believers'</b>" };
DATA[DATA.length] = { id: "rune_rohling",	rohling: "Quest: <b>'Snappers Claws'</b>" };
DATA[DATA.length] = { id: "rune_rohling",	rohling: "Quest: <b>'Fernando's business'</b>" };
DATA[DATA.length] = { id: "rune_rohling",	rohling: "Quest: <b>'Lurker Hunt'</b>" };
DATA[DATA.length] = { id: "rune_rohling",	rohling: "Quest: <b>'I gotta get out of here!'</b>" };
DATA[DATA.length] = { id: "rune_rohling",	rohling: "Quest: <b>'A package of lock picks'</b>" };
DATA[DATA.length] = { id: "rune_rohling",	rohling: "You find one blank Rune in <b>Xardas old Tower in the Valley of Mines</b> on a table on the last floor." };
DATA[DATA.length] = { id: "rune_rohling",	rohling: "You get a blank Rune from <b>Milten</b> in the <b>Castle</b> when you ask for Stuff." };
DATA[DATA.length] = { id: "rune_rohling",	rohling: "In the <b>Secret Library</b> on a table where are the Sea Map and the Tears of Innos." };
DATA[DATA.length] = { id: "rune_rohling",	rohling: "You get a blank Rune from <b>Parlan</b> when you become a Mage." };
DATA[DATA.length] = { id: "rune_rohling",	rohling: "A <b>blank rune</b> can be found in the water at the beach in the north of the pirates camp." };
DATA[DATA.length] = { id: "rune_rohling",	rohling: "<b>Hidden blank rune in Jharkendar</b>" };
DATA[DATA.length] = { id: "rune_rohling",	rohling: "Buy it from <b>several Traders</b>" };
